debug: true
server:
  port: 3010

okta:
  oauth2:
    # Replace with the domain of your Auth0 tenant.
    issuer: https://dev-w0iek25yfj2hestf.us.auth0.com/
    # Replace with the API Identifier for your Auth0 API.
    audience: https://dev-w0iek25yfj2hestf.us.auth0.com/api/v2/
