@startuml
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

SHOW_PERSON_OUTLINE()

'Actors
Person(travelAgent, "Travel Agent", "Helps travelers plan their trips")
Person(traveler, "Traveler", "Can book, cancel, modify, and pay for trips")

'Containers within the system
System_Boundary(c4, "Triptrop") {
    Container(webApp, "Web Application", "React.js", "User interface for travelers")
    Container(adminApp, "Admin Application?", "?", "User interface for travel agents?")
    Container(backend, "Backend", "Java", "Processes all logic")
    Container(DB, "Database", "?", "Stores data")
}

'APIs
System_Ext(wireMock, "WireMock", "API for web application testing")
System_Ext(bookingAPI, "Booking API", "API for booking trips via Booking.com")
System_Ext(tripAdvisor, "TripAdvisor API", "API for booking trips via TripAdvisor")
System_Ext(airbnb, "Airbnb API", "API for booking accommodations via Airbnb")
System_Ext(smsGateway, "SMS Gateway API", "API for sending SMS messages")
System_Ext(emailVerifier, "Email Verifier API", "API for verifying email addresses")
System_Ext(veriphone, "Veriphone API", "API for verifying phone numbers")
System_Ext(PayPal, "PayPal API", "API for processing payments via PayPal")
System_Ext(Stripe, "Stripe API", "API for processing payments via Stripe")
System_Ext(NS, "NS API", "API for booking train journeys via NS")
System_Ext(CarBooks, "CarBooks API", "API for booking car rentals via CarBooks")


'Relationships
Rel(travelAgent, adminApp, "Uses", "HTTP")
Rel(webApp, backend, "Sends data to", "HTTP")
Rel(adminApp, backend, "Sends data to", "HTTP")
Rel(traveler, webApp, "Books, cancels, modifies, and pays for trips")
Rel(travelAgent, webApp, "Helps travelers plan their trips")

Rel(backend, wireMock, "Mocks APIs for testing")
Rel(webApp, bookingAPI, "Makes API requests to")
Rel(webApp, tripAdvisor, "Makes API requests to")
Rel(webApp, airbnb, "Makes API requests to")
Rel(backend, smsGateway, "Makes API requests to")
Rel(backend, emailVerifier, "Makes API requests to")
Rel(backend, veriphone, "Makes API requests to")
Rel(backend, PayPal, "Makes API requests to")
Rel(backend, Stripe, "Makes API requests to")
Rel(backend, NS, "Makes API requests to")
Rel(backend, CarBooks, "Makes API requests to")

Rel(backend, DB, "Reads and writes")


@enduml