###
POST http://localhost:8080/api/payments/process?amount=10.00&paymentType=paypal


###

POST http://localhost:8080/api/payments/process?amount=10.00&paymentType=stripe


###

GET http://localhost:8080/traveldata?locationStart=Nijmegen&locationEnd=Oss&transportType=TRAIN

###

GET http://localhost:8080/traveldata?locationStart=Nijmegen&locationEnd=Arnhem&transportType=CAR

###


POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "edevries",
  "password": "3g2Rw9sT1x"
}

###

