@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Sequence.puml

autonumber

actor Traveler
System_Boundary(c4, "Triptrop")
Container(webApp, "Web applicatie", "React.js", "Gebruikersinterface voor reizigers")
Container(backend, "Backend", "Java", "Verwerkt alle logica")
Boundary_End()
System_Ext(wireMock, "WireMock", "API voor webapplicatie")


Traveler -> webApp : Submits username and password
webApp -> backend : sends username and password
backend -> wireMock : Sends username and password
wireMock --> backend : returns token
backend --> webApp : Sends authentication response
webApp --> Traveler : Displays login result

@enduml

