@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Sequence.puml

autonumber

' actoren en containers
actor "reiziger (auth-ed)" as R
System_Boundary(c4, "Triptrop")
Container(webApp, "Web applicatie", "React.js", "Gebruikersinterface voor reizigers")
Container(backend, "Backend", "Java", "Verwerkt alle logica")
Container(DB, "Database", "?", "Opslaan van data")
Boundary_End()
System_Ext(API, "Booking API", "?")

' relaties
R -> webApp: Books a trip on Triptrop
webApp -> backend: Books a trip with details
backend -> API: Books a trip with details
API -> backend: Confirms booking
backend -> DB: Stores booking
backend -> webApp: Confirms booking
webApp -> R: Shows confirmed booking

@enduml